import './js/main-slider.js'
import './js/burger.js'
import './js/header-nav.js'
import './js/booking.js'
import './js/detailes.js'
import './js/lift-up.js'
import './js/contacts.js'
import './js/learn.js'
import './index.scss'

